// <auto-generated />

using System.CodeDom.Compiler;
using System.Resources;
using System.Data.Entity.Migrations.Infrastructure;
namespace Dp.EntityFramework.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changetoday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetoday));
        
        string IMigrationMetadata.Id
        {
            get { return "201803170614171_change-today"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
